services:
  oracle:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: jonathan-carvalho-oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=admin
      - APP_USER=admin
      - APP_USER_PASSWORD=admin

